### ISSUE TITLE
unkown scale 

### ISSUE THREAD

**Issue by wuneng** [LizhenWangT/FaceVerse#1]
The interocular distance of  pca template is 0.55. How to covert it to unit(e.g. mm)?

**Comment by LizhenWangT** [comment]
Actually we rescale the models by converting the length along the y axis to 1. So you can get a reasonable scale by multiplying the coordinates by factors of 200mm to 250mm.

**Comment by wuneng** [comment]
I want to fit rgbd data using FaceVerse model. With unknow scale, the fitting results can not be accurate. Multiplying 200 means a person whose interocular distance would be 110mm(beyond the normal range of the human interocular distance 8.5cm-10.5cm)

**Comment by LizhenWangT** [comment]
Maybe an optimizable scale parameter will be helpful in this case, since there is no sclae-related components in our ''idBase'' matrix.

**Comment by wuneng** [comment]
Get it, thanks for your suggestion.
