### ISSUE TITLE
Could you upload the model files onto Baidu netdisk ?

### ISSUE THREAD

**Issue by huhai463127310** [LizhenWangT/FaceVerse#13]
FaceVerse is a great work. And thanks for your open source. But I can't download  the model files becaause google drive limited quota. Could you upload the model files onto Baidu netdisk. It's more convenient for Chinese users. That's the error :   

>抱歉，您目前无法查看或下载此文件。  
>最近查看或下载此文件的用户过多。请稍后再尝试访问此文件。如果您尝试访问的文件特别大或已与很多人共享，那么您最长可能需要等待 24 小时才能查看或下载该文件。如果您在 24 小时后仍然无法访问文件，请与您的网域管理员联系。

**Comment by LizhenWangT** [comment]
Done. Please check the ReadMe again.

**Comment by huhai463127310** [comment]
> Done. Please check the README file.

It's great ! Thanks very much.
