### ISSUE TITLE
Handling Video Input

### ISSUE THREAD

**Issue by JamesBrod** [LizhenWangT/FaceVerse#8]
Hi! 
Really cool work! I was wondering if you're offline tracking does anything special in terms of stabilisation? I've noticed that using the image input demo across frames of a video leads to the mesh being more shakey compared to the specific tracking script and was wondering how you handled it.

Thanks!

**Comment by LizhenWangT** [comment]
Hi, thank you. I think there are three main reasons:
1. The landmarks detected by OpenSeeFace are stable in videos.
2. The initial tracking parameters of the current frame is already optimized by the previous frame, which makes the optimization much easier.
3. The differentiable rendering loss provides stable contraints and is vital for stability.

**Comment by JamesBrod** [comment]
Ok, great! I thought something like that was the case. Thanks for getting back to me so quickly!
